/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5426468d-86c6-4dfe-81bf-0148752951c4
-/

/-
We define `is_root y x` to be the property that `x` is a root of the given equation for a constant `y`.
We define `solution_set y` as the set of `x` such that `x` is a perfect square `k^2` (with `x+y ≥ 0`) or `x+y` is a perfect square `k^2` (with `x ≥ 0`).
We prove `solution_set_correct` which states that `x` is a root if and only if `x` is in `solution_set y`.
The formula for the roots is thus: $x = k^2$ for some $k \in \mathbb{N}$ such that $k^2 + y \ge 0$, or $x = k^2 - y$ for some $k \in \mathbb{N}$ such that $k^2 - y \ge 0$.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The set of roots x for a given y is the union of {k^2 | k ∈ ℕ, k^2 + y ≥ 0} and {k^2 - y | k ∈ ℕ, k^2 - y ≥ 0}.
-/
def is_root (y x : ℝ) : Prop :=
  0 ≤ x ∧ 0 ≤ x + y ∧
  Real.cos (Real.sqrt x * 2 * Real.pi) * Real.cos (Real.sqrt (x + y) * 2 * Real.pi) =
  Real.cos (Real.sqrt x * 2 * Real.pi) + Real.cos (Real.sqrt (x + y) * 2 * Real.pi) - 1

def solution_set (y : ℝ) : Set ℝ :=
  {x | (∃ k : ℕ, x = k ^ 2 ∧ 0 ≤ x + y) ∨ (∃ k : ℕ, x = k ^ 2 - y ∧ 0 ≤ x)}

theorem solution_set_correct (y : ℝ) :
  ∀ x, x ∈ solution_set y ↔ is_root y x := by
    unfold solution_set is_root;
    intro x; constructor;
    · rintro ( ⟨ k, rfl, hk ⟩ | ⟨ k, rfl, hk ⟩ ) <;> norm_num [ mul_assoc ];
      · exact?;
      · linarith;
    · field_simp;
      rintro ⟨ hx, hy, h ⟩;
      -- If $\cos(\sqrt{x} \cdot 2\pi) = 1$ or $\cos(\sqrt{x+y} \cdot 2\pi) = 1$, then $x$ or $x+y$ must be a perfect square.
      by_cases h_cos_x : Real.cos (Real.sqrt x * 2 * Real.pi) = 1;
      · -- If $\cos(\sqrt{x} \cdot 2\pi) = 1$, then $\sqrt{x} \cdot 2\pi = 2k\pi$ for some integer $k$, implying $\sqrt{x} = k$.
        obtain ⟨k, hk⟩ : ∃ k : ℤ, Real.sqrt x = k := by
          rw [ Real.cos_eq_one_iff ] at h_cos_x; obtain ⟨ k, hk ⟩ := h_cos_x; exact ⟨ k, by nlinarith [ Real.pi_pos ] ⟩ ;
        exact Or.inl ⟨ k.natAbs, by simp +decide [ ← hk, hx ], hy ⟩;
      · -- If $\cos(\sqrt{x+y} \cdot 2\pi) = 1$, then $x+y$ must be a perfect square.
        have h_cos_xy : Real.cos (2 * Real.pi * Real.sqrt (x + y)) = 1 := by
          cases lt_or_gt_of_ne h_cos_x <;> nlinarith [ Real.cos_le_one ( Real.sqrt x * 2 * Real.pi ), Real.cos_le_one ( 2 * Real.pi * Real.sqrt ( x + y ) ) ];
        -- If $\cos(\sqrt{x+y} \cdot 2\pi) = 1$, then $\sqrt{x+y}$ must be an integer.
        obtain ⟨k, hk⟩ : ∃ k : ℤ, Real.sqrt (x + y) = k := by
          rw [ Real.cos_eq_one_iff ] at h_cos_xy; obtain ⟨ k, hk ⟩ := h_cos_xy; exact ⟨ k, by nlinarith [ Real.pi_pos ] ⟩ ;
        exact Or.inr ⟨ k.natAbs, by norm_num [ ← @Nat.cast_inj ℝ, ← hk, Real.sq_sqrt hy ], hx ⟩