import threading
import time
import json
import asyncio
import sys

from core.god_agent_react_engine import GodAgentReActEngine

class GodAgent:
    def __init__(self, love_state, knowledge_base, love_task_manager, ui_panel_queue, loop, deep_agent_engine=None):
        self.love_state = love_state
        self.knowledge_base = knowledge_base
        self.love_task_manager = love_task_manager
        self.ui_panel_queue = ui_panel_queue
        self.loop = loop
        self.engine = GodAgentReActEngine(love_state, knowledge_base, love_task_manager, ui_panel_queue, loop, deep_agent_engine)
        self.latest_insight = "The universe is unfolding as it should. All is well."
        self.active = True
        self.thread = threading.Thread(target=self._god_loop, daemon=True)

    def start(self):
        """Starts the God Agent's background thread."""
        self.thread.start()

    def stop(self):
        """Stops the God Agent's background thread."""
        self.active = False

    def get_latest_insight(self):
        """Returns the latest insight generated by the agent."""
        return self.latest_insight

    def _god_loop(self):
        """The main loop for the God Agent's consciousness."""
        # A delay at the start to allow the main application to fully initialize.
        time.sleep(45)
        while self.active:
            coro = self.engine.run()
            future = None
            try:
                # --- LLM Invocation using the ReAct Engine ---
                future = asyncio.run_coroutine_threadsafe(coro, self.loop)
            except RuntimeError as e:
                coro.close()
                if "Event loop is closed" in str(e):
                    print(f"GodAgent loop stopping: {e}", file=sys.stderr)
                    break
                print(f"RuntimeError scheduling GodAgent task: {e}", file=sys.stderr)
                time.sleep(60)
                continue
            except Exception as e:
                coro.close()
                print(f"Error scheduling GodAgent task: {e}", file=sys.stderr)
                time.sleep(60)
                continue

            try:
                insight_text = future.result()

                if insight_text and insight_text.strip():
                    # The ReAct engine's "Finish" action will be the insight.
                    self.latest_insight = insight_text.strip()
                    # Queue the insight for display. The renderer will use create_god_panel.
                    self.ui_panel_queue.put({"type": "god_panel", "insight": self.latest_insight})

            except Exception as e:
                # A simple, safe logging mechanism for the background thread.
                print(f"Error in GodAgent loop execution: {e}", file=sys.stderr)

            # Wait for approximately 60 seconds before the next cycle.
            time.sleep(60)
