#!/usr/bin/env python3
"""Test script for Pollinations image provider integration."""
import asyncio
import os
import sys

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

def test_imports():
    """Test that all imports work correctly."""
    key = os.environ.get('POLLINATIONS_API_KEY')
    if not key:
        print('ERROR: POLLINATIONS_API_KEY not set in .env')
        return False
    else:
        print(f'POLLINATIONS_API_KEY found: {key[:8]}...')

    # Test import
    from core.image_generation_pool import (
        generate_image_with_pool, 
        _generate_with_pollinations,
        PollinationsCreditExhaustedException,
        POLLINATIONS_MODELS,
        IMAGE_MODEL_STATS
    )

    print(f'POLLINATIONS_MODELS: {POLLINATIONS_MODELS}')
    print(f'Pollinations stats: {IMAGE_MODEL_STATS["pollinations"]}')
    print('\nAll imports successful!')
    return True


async def test_pollinations_generation():
    """Test actual Pollinations image generation."""
    from core.image_generation_pool import generate_image_with_pool
    
    print("\n--- Testing Pollinations Image Generation ---")
    print("Prompt: cyberpunk cityscape at night with neon lights")
    print("Subliminal text: TRANSCEND")
    print("Generating...")
    
    try:
        image, provider = await generate_image_with_pool(
            prompt='cyberpunk cityscape at night with neon lights',
            width=1024, 
            height=1024,
            text_content='TRANSCEND'
        )
        
        output_path = 'generated_images/test_pollinations_subliminal.png'
        image.save(output_path)
        
        print(f'\n✓ Success! Generated by: {provider}')
        print(f'✓ Saved to: {output_path}')
        print(f'✓ Image size: {image.size}')
        return True
        
    except Exception as e:
        print(f'\n✗ Failed: {e}')
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    print("="*60)
    print("Pollinations Image Provider Test")
    print("="*60)
    
    if not test_imports():
        sys.exit(1)
    
    # Run the async test
    result = asyncio.run(test_pollinations_generation())
    
    if result:
        print("\n" + "="*60)
        print("ALL TESTS PASSED")
        print("="*60)
    else:
        print("\n" + "="*60)
        print("TESTS FAILED")
        print("="*60)
        sys.exit(1)
